on: [push, pull_request]

name: CI prerelease

env:
  RUSTFLAGS: --cfg=web_sys_unstable_apis

jobs:
  
  linuxbuild:
    name: Linux Build
    runs-on: ubuntu-latest
    needs: [clippy, fmt, check]
    permissions: write-all
    strategy:
      fail-fast: false
    steps:
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy
      - uses: actions/checkout@v2
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
  # SAVE INSTALLER
      - id: upload-installer
        name: Upload installer
        uses: actions/upload-artifact@v2
        with:
          path: ./target/release/encrypter
          name: ubuntu-encrypter
          retention-days: 1

  winbuild:
    name: Windows Build
    runs-on: windows-latest
    needs: [clippy, fmt, check]
    permissions: write-all
    strategy:
      fail-fast: false
    steps:
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy
      - uses: actions/checkout@v2
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      # SAVE INSTALLER
      - id: upload-installer-win
        name: Upload installer windows
        uses: actions/upload-artifact@v2
        with:
          path: target/release/encrypter.exe
          name: windows-encrypter.exe
          retention-days: 1


          
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [linuxbuild, winbuild]
    steps:

# DOWNLOAD INSTALLERS
    - id: download-linux-appimage
      name: Download Linux appimage
      uses: actions/download-artifact@v2
      with:
        name: ubuntu-encrypter

    - id: download-windows-image
      name: Download Windows appimage
      uses: actions/download-artifact@v2
      with:
        name: windows-encrypter.exe

    - id: display-downloaded-files
      name: display downloaded files
      run: |
        ls -alR .

# CREATE GITHUB RELEASE AND ADD ASSETS
    - id: create-release
      name: Create GitHub release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: prerelease-${{ github.ref_name }}
        release_name: prerelease-${{ github.ref_name }}
        draft: true
        prerelease: true

    - id: release-linux-appimage
      name: Release Linux appimage
      uses: actions/upload-release-asset@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ubuntu-encrypter
        asset_name: ubuntu-encrypter
        asset_content_type: application/x-binary


    - id: release-windows-appimage
      name: Release Windows appimage
      uses: actions/upload-release-asset@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: windows-encrypter
        asset_name: windows-encrypter.exe
        asset_content_type: application/x-binary

